// eslint-disable-next-line import/no-anonymous-default-export
export default ( [
    {
        id: 1,
        postedOn: new Date(),
        title: 'Frontend Developer',
        description: 'Full Time',
        tags: ['Javascript', 'React.js', 'Node.js' ],
        image: 'https://google.com/careers',
    },
    {
        id: 1,
        postedOn: new Date(),
        title: 'Frontend Developer',
        description: 'Full Time',
        tags: ['Javascript', 'React.js', 'Node.js' ],
        image: 'https://google.com/careers',
    },
    {
        id: 1,
        postedOn: new Date(),
        title: 'Frontend Developer',
        description: 'Full Time',
        tags: ['Javascript', 'React.js', 'Node.js' ],
        image: 'https://google.com/careers',
    },
    {
        id: 1,
        postedOn: new Date(),
        title: 'Frontend Developer',
        description: 'Full Time',
        tags: ['Javascript', 'React.js', 'Node.js' ],
        image: 'https://google.com/careers',
    },
    {
        id: 1,
        postedOn: new Date(),
        title: 'Frontend Developer',
        description: 'Full Time',
        tags: ['Javascript', 'React.js', 'Node.js' ],
        image: 'https://google.com/careers',
    },
    {
        id: 1,
        postedOn: new Date(),
        title: 'Frontend Developer',
        description: 'Full Time',
        tags: ['Javascript', 'React.js', 'Node.js' ],
        image: 'https://google.com/careers',
    },
       {
        id: 1,
        postedOn: new Date(),
        title: 'Frontend Developer',
        description: 'Full Time',
        tags: ['Javascript', 'React.js', 'Node.js' ],
        image: 'https://google.com/careers',
    },
    {
        id: 1,
        postedOn: new Date(),
        title: 'Frontend Developer',
        description: 'Full Time',
        tags: ['Javascript', 'React.js', 'Node.js' ],
        image: 'https://google.com/careers',
    },
    {
        id: 1,
        postedOn: new Date(),
        title: 'Frontend Developer',
        description: 'Full Time',
        tags: ['Javascript', 'React.js', 'Node.js' ],
        image: 'https://google.com/careers',
    },
   
] );